{
  "hash": "28602398a77dbecbb9604295028f129c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Final exam review\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"04-21-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 24-final-exam-review-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements\n\n-   Project report and organized GitHub repo - due Wednesday, April 22 at 11:59pm\n\n-   Course and TA evaluations - open until April 25 at 11:59pm\n\n-   Final exam: April 30, 9am - 12pm\n\n## Project\n\nAny questions about the project?\n\n## Course evaluations\n\nPlease share your feedback about the course!\n\nCourse evaluations [**and**]{.underline} TA evaluations are open now until April 25 at 11:59pm.\n\n-   If the response rate is at least 80% on both course evaluations [**and**]{.underline} TA evaluations, everyone in the class will receive 0.5 points (out of 50) added to their final exam grade.\n\n-   Check email for links to course and TA evaluations.\n\n## Final exam\n\n-   In-class only: April 30, 9am - 12pm\n\n-   Cumulative exam covering content from the full semester\n\n-   Format similar to Exam 01 and Exam 02\n\n-   Official university documentation or dean's excuse required to excuse the exam\n\n-   Can bring one page (front and back) of handwritten notes written directly on paper\n\n    -   Turn in with the exam\n\n    -   Point deductions for notes that don't follow rules\n\n## Topics {.midi}\n\n::::: columns\n::: {.column width=\"50%\"}\n**Linear regression**\n\n-   Fitting and interpreting models\n-   Model evaluation\n-   Different types of predictors\n-   Inference\n-   Matrix representation of regression\n-   Model conditions and diagnostics\n-   Multicollinearity\n-   Variable transformations\n:::\n\n::: {.column width=\"50%\"}\n-   Maximum likelihood estimation\n-   Properties of estimators\n-   Model selection\n-   Ridge regression\n\n**Logistic regression**\n\n-   Fitting and interpreting models\n-   Predicted probabilities and classes\n-   ROC curve and AUC\n-   Inference\n-   Model selection\n\n**Data science ethics**\n:::\n:::::\n\n## Tips for studying {.midi}\n\n-   Rework derivations from assignments and lecture notes\n\n-   Review in-class activities and assignments, asking \"why\" as you review your process and reasoning\n\n-   Focus on understanding not memorization\n\n-   Explain concepts / process to others\n\n-   Ask questions in office hours\n\n-   Review prepare readings\n\n-   Review lecture recordings (available until start of final exam)\n\n## Resources\n\n-   Prepare readings\n\n-   Lecture notes\n\n-   Lecture recordings available until start of exam\n\n-   HW and lab assignments (all solutions on Canvas)\n\n-   Exam 01 and Exam 02 practice problems\n\n# Practice\n\n## Logistic regression response variable\n\n$Y$ is a binary response variable.\n\n-   What is the distribution of $Y$?\n\n-   What is the variance of $y_i$, given the logistic regression model?\n\n-   Why doesn't constant variance hold for logistic regression?\n\n## Logistic regression coefficients\n\nLet $\\pi_i$ be the probability an individual is diagnosed with lung cancer. We fit the model\n\n$$\n\\log\\Big(\\frac{\\hat{\\pi}_i}{1-\\hat{\\pi}_i}\\Big) = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\text{birdkeepingYes}\n$$\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term        | estimate|\n|:-----------|--------:|\n|(Intercept) |   -1.386|\n|birdYes     |    1.356|\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n-   Explain what -1.386 tells us.\n\n-   Explain what 1.356 tells us.\n:::\n:::::\n\n## Logistic regression odds ratios\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Birdkeeping | Cancer| No Cancer|\n|:-----------|------:|---------:|\n|No          |     16|        64|\n|Yes         |     33|        34|\n\n\n:::\n:::\n\n\n## Drop-in-deviance test\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                                                    | df.resid| deviance| df|  G| p.value|\n|:-------------------------------------------------------|--------:|--------:|--:|--:|-------:|\n|cancer ~ socioeconomic + age + bird                     |      143|      172| NA| NA|      NA|\n|cancer ~ socioeconomic + age + bird + yrsmoke + cigsday |      141|      155|  2| 17|       0|\n\n\n:::\n:::\n\n\n-   What is the distribution of the test statistic $G$?\n\n-   How would do we know the p-value will be very small?\n\n## Unbiased estimator\n\n-   What does it mean for an estimator to be unbiased?\n\n-   How do you show an estimator is unbiased?\n\n## Linear regression\n\n$$\n\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}\n$$\n\n-   What assumptions on $\\boldsymbol{\\epsilon}$ are needed to derive the least-squares estimator?\n\n-   What assumptions on $\\boldsymbol{\\epsilon}$ are needed to conduct inference for $\\boldsymbol{\\beta}$ ?\n\n-   What assumptions on $\\boldsymbol{\\epsilon}$ are needed to derive the MLE for $\\boldsymbol{\\beta}$?\n\n## Sum of squares\n\n$$\n\\text{Show }\\hspace{1mm} SSR = \\mathbf{y}^\\mathsf{T}\\mathbf{y} - \\hat{\\boldsymbol{\\beta}}^\\mathsf{T}\\mathbf{X}^\\mathsf{T}\\mathbf{y}\n$$\n\n## Types of predictors\n\n-   Why might we use centered predictors in a model?\n\n-   Why might we use standardized predictors in a model?\n\n# Questions?\n",
    "supporting": [
      "24-final-exam-review_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}