---
title: "Exam 02 review"
author: "Prof. Maria Tackett"
date: "04-09-2026"
date-format: "MMM DD, YYYY"
footer: "[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
  html: 
    output-file: 23-exam-02-review-notes.html
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

```{r setup, include=FALSE, echo=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
	fig.align = "center",
	fig.height =5,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)
```

## Announcements

-   HW 04 due Thursday, April 9 at 11:59pm

-   Next project milestone: Draft report due Friday, April 10 (before lab)

    -   Peer feedback due April 11 at 11:59pm

-   Exam 02

    -   In-class: April 14

    -   Take-home: April 14 - 16

    -   Content: February 19 (Model conditions & diagnostics) - Today (Data science ethics)

## Exam 02 format

-   50 points total

    -   In-class: 36 points

    -   Take-home: 15 points

-   In-class: 75 minutes during April 14 lecture

-   Take-home: due Thursday, April 16 at 12pm (noon)

-   Official university documentation or note from your academic dean required to excuse any part of the exam

## Exam 02 content {.midi}

Concepts from the first half of the semester continue to apply, but the exam will focus on new content since Exam 01.

::::: columns
::: {.column width="50%"}
**Linear regression**

-   Model conditions and diagnostics

-   Multicollinearity

-   Variable transformations

-   Maximum likelihood estimation

-   Properties of estimators

-   Model selection

-   Ridge regression
:::

::: {.column width="50%"}
**Logistic regression**

-   Fitting and interpreting logistic model
-   Predicted probabilities and classes
-   ROC curve and AUC
-   Inference for logistic regression
-   Model selection

**Data science ethics**
:::
:::::

## Tips for studying {.midi}

-   Rework derivations from assignments and lecture notes

-   Review in-class activities and assignments, asking "why" as you review your process and reasoning

-   Focus on understanding not memorization

-   Explain concepts / process to others

-   Ask questions in office hours

-   Review prepare readings

-   Review lecture recordings (available until start of in-class exam)

## Resources

-   Prepare readings

-   Lecture notes, AEs, labs, homework

-   Lecture recordings available until start of the exam (link in course website menu)

-   HW and lab assignments

-   Exam 02 practice problems (link in menu of course website)

# Application exercise

::: appex
📋 [sta221-sp26.github.io/ae/ae-06-exam-02-review](https://sta221-sp26.github.io/ae/ae-06-exam-02-review)
:::
