---
title: "Project: Research Topics"
date: "02-06-2026"
date-format: "MMM DD, YYYY"
footer: "[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Today's agenda

-   AE 03 (Part 1)
-   Final project - research topics

## AE 03

::: appex
📋 [sta221-sp26.github.io/ae/ae-03-inference](../ae/ae-03-inference.html)

**Part 1**
:::

## Final team project {.midi}

-   **Goal**: Use the methods from STA 221 to analyze data and answer a research question developed by your team

-   **Primary deliverables:**

    1.  an in-person presentation about the exploratory data analysis and initial modeling

    2.  a written, reproducible report detailing your analysis and results

    3.  a GitHub repository containing all work from the project

-   There are periodic project milestones throughout the semester to help you work towards these deliverables

## Today's focus: Research topics {.midi}

-   **Goals:** Identify three potential research topics your team is interested in investigating and draft research questions.

-   You do [**not**]{.underline} need to have a data set at this point

-   You can discuss the topics you put in the Get to Know You survey to help generate ideas

-   **Submission**: All work for the project will be submitted in your team’s project GitHub repo. You will receive feedback via an Issue on GitHub to model a workflow typically used in practice.

    -   There is no Gradescope submission.

🔗 <https://sta221-sp26.github.io/project>
