---
title: "Lab 05"
subtitle: "Expanding multiple linear regression"
date: "02-27-2026"
date-format: "MMM DD, YYYY"
footer: "[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

# Welcome

## Today's lab

-   Mid-semester survey
-   Lab 05: Expanding multiple linear regression

## Mid-semester feedback

-   **Purpose**: To give the teaching team feedback on what is working well (or not as well) in helping you learn the course content

-   The feedback is **anonymous**

-   Please take a few minutes to fill it out during lab today

**The teaching team appreciates your feedback!**

🔗 UPDATE LINK!

## Lab 05: Expanding multiple linear regression

This lab focuses on

-   modeling complex data using variable transformations, categorical predictors and interactions, and various model specifications.

-   evaluating model diagnostics and conditions.

🔗 [sta221-sp26.github.io/labs/lab-05.html](https://sta221-sp26.github.io/labs/lab-05.html)

## Reminder: Tips for working on a team

-   Do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.

-   The labs are structured to help you learn the steps of a data analysis. Do not split up the lab among the team members; work on it together in its entirety.

-   Everyone has something to contribute! Use the lab groups as an opportunity to share ideas and learn from each other.
