{
  "hash": "20952ca180d6c8776812df7ec569e293",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Exam 01 practice\n---\n\n::: callout-important\nThis page contains practice problems to help prepare for Exam 01. This set of practice problems is <u>**not**</u> comprehensive.\\\n\\\nThere is no answer key for these problems. You are encouraged to ask questions during office hours or on Ed Discussion.\n:::\n\n## Exercise 1\n\n\n\nWe will use data from 342 penguins at Palmer Station in Antarctica to fit linear regression model using species (Adelie, Chinstrap, or Gentoo), flipper length (in millimeters), and bill depth (in millimeters) to predict the body mass of penguins (in grams). [Click here](https://allisonhorst.github.io/palmerpenguins/reference/penguins.html) to read more about the variables.\n\nThe linear regression model has the form\n\n$$\n\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}\n$$Write the dimensions of $\\mathbf{y}, \\mathbf{X},\\boldsymbol{\\beta}, \\boldsymbol{\\epsilon}$ specifically for this analysis.\n\n## Exercise 2\n\nThe output for the model described in Exercise 1, along with 95% confidence intervals for the model coefficients, is shown below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_fit <- lm(body_mass_g ~ species + flipper_length_mm + \n                     bill_depth_mm, \n                   data = penguins)\n\ntidy(penguins_fit, conf.int = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term              |  estimate| std.error| statistic| p.value|  conf.low| conf.high|\n|:-----------------|---------:|---------:|---------:|-------:|---------:|---------:|\n|(Intercept)       | -4526.887|   516.931|    -8.757|   0.000| -5543.705| -3510.068|\n|speciesChinstrap  |  -131.968|    51.400|    -2.567|   0.011|  -233.073|   -30.863|\n|speciesGentoo     |  1288.968|   132.774|     9.708|   0.000|  1027.798|  1550.138|\n|flipper_length_mm |    25.700|     3.098|     8.295|   0.000|    19.606|    31.794|\n|bill_depth_mm     |   182.364|    18.358|     9.934|   0.000|   146.252|   218.475|\n\n\n:::\n:::\n\n\n-   Interpret the coefficient of `flipper_length_mm` in the context of the data.\n\n-   What is the baseline category for `speices`?\n\n-   Interpret the coefficient of `speciesChinstrap` in the context of the data.\n\n## Exercise 3\n\n-   Does the intercept have a meaningful interpretation?\n\n-   If not, what are some strategies we can use to fit a model in which the intercept is meaningful?\n\n## Exercise 4\n\nThere are three species in the data set (Adelie, Chinstrap, Gentoo), but only two terms for species in the model. Use the design matrix to show why we cannot put indicators for all three species along with the intercept in the model.\n\n## Exercise 5\n\nWe conduct the following hypothesis test for the coefficient of `flipper_length_mm`.\n\n-   **Null:** There is no linear relationship between flipper length and body mass, after accounting for species and bill depth\n\n-   **Alternative**: There is a linear relationship between flipper length and body mass, after accounting for species and bill depth\n\na.  Write these hypotheses in mathematical notation.\nb.  The standard error is 3.098. Explain how this value is computed and what this value means in the context of the data.\nc.  The test statistic is 8.295. Explain how this value is computed and what this value means in the context of the data.\nd.  What distribution is used to compute the p-value?\ne.  What is the conclusion from the test in the context of the data?\n\n## Exercise 6\n\n1.  Interpret the 95% confidence interval for `flipper_length_mm` in the context of the data.\n2.  Is the interval consistent with the test from the previous exercise? Briefly explain.\n\n## Exercise 7\n\nSketch a scatterplot of the relationship between bill depth and body mass that shows the effect of bill depth differing by species.\n\n## Exercise 8\n\nWhen we conduct inference for regression, we assume the following distribution for $\\mathbf{y}|\\mathbf{X}$\n\n$$\n\\mathbf{y}|\\mathbf{X} \\sim(\\mathbf{X}\\boldsymbol{\\beta}, \\sigma^2_\\epsilon\\mathbf{I})\n$$\n\na.  Show that $E(\\mathbf{y}|\\mathbf{X}) = \\mathbf{X}\\boldsymbol{\\beta}$\nb.  Show that $Var(\\mathbf{y}|\\mathbf{X})= \\sigma^2_{\\epsilon}\\mathbf{I}$\n\nSee the lecture [Inference for Regression](../slides/07-inference.html) to check your work.\n\n## Exercise 9\n\nWe conduct inference on the coefficients $\\boldsymbol{\\beta}$ assuming that the variability of $\\mathbf{y}|\\mathbf{X}$ is equal for all values (or combination of values) of the predictor(s). Briefly explain why this assumption is important.\n\n## Exercise 10\n\nGiven the model $\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}$, derive the least-squares estimator $\\hat{\\boldsymbol{\\beta}}$ using matrix calculus.\n\nSee the lecture [SLR: Matrix representation](../slides/04-slr-matrix.html) to check your work.\n\n## Exercise 11\n\nGiven the model $\\mathbf{y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}$, derive the least-squares estimator $\\hat{\\boldsymbol{\\beta}}$ using the geometric interpretation of the model.\n\nSee the lecture [SLR: Matrix representation](../slides/04-slr-matrix.html) to check your work.\n\n## Exercise 12\n\nExplain why we say \"holding all else constant\" when interpreting the coefficients in a multiple linear regression model.\n\n## Exercise 13\n\nSuppose we have two models:\n\n-   Model 1 includes predictors $X_1$ and $X_2$\n\n-   Model 2 includes predictors $X_1, X_2, X_3$ and $X_4$\n\nExplain why we should use $Adj. R^2$ and not $R^2$ to compare these models.\n\n## Exercise 14\n\nRework Exercises 1 - 5 in [HW 01](/hw/hw-01.html) for more practice with theory and math.\n\n## Exercise 15\n\nRework Exercises 1 - 4 in [HW 02](/hw/hw-02.html) for more practice with theory and math.\n\n## Exercise 16\n\nAssume $Var(\\boldsymbol{\\epsilon})$ = $\\mathbf{XV}$, such that $\\mathbf{V}$ has the appropriate dimensions. Derive $Var(\\hat{\\boldsymbol{\\beta}})$. What are the dimensions of $\\mathbf{V}$?\n\n## Relevant lectures, assignments and AEs\n\nAsk yourself \"why\" questions as you review the slides, along with your answers, problem-solving process, and derivations on the lectures and assignments. It can also be helpful to explain your process to others.\n\n-   Lectures: January 8 - February 12 (February 12 lecture is an exam review)\n\n-   HW 01 - 02\n\n-   Lab 01 - 04 (Lab 04 is an exam review)\n\n-   AE 01 - 04 (AE 04 is an exam review)\n",
    "supporting": [
      "exam-01-practice_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}