{
  "hash": "6ae0519925b6570c8b6dffaf745992fd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"03-24-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 18-logistic-regression-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n## Announcements {.midi}\n\n-   Lab 06 due TODAY at 11:59pm\n\n-   Project presentations in lab on Friday, March 27\n\n-   Statistics experience due April 2\n\n<!-- -->\n\n-   SSMU Data Mini #3 - April 4 (after statistics experience deadline)\n\n    -   See [Ed Discussion](https://edstem.org/us/courses/90766/discussion/7845073) for full announcement\n\n## Topics\n\n-   Introduce logistic regression for binary response variable\n\n-   Use maximum likelihood estimation to derive $\\hat{\\boldsymbol{\\beta}}$\n\n-   Interpret coefficients of logistic regression model\n\n## Computational setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(Stat2Data) #contains data set\nlibrary(patchwork)\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `high_risk`: 1 = High risk of having heart disease in next 10 years, 0 = Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n\n::: {.cell}\n\n:::\n\n\n## Data: `heart_disease`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,135 × 3\n     age education high_risk\n   <dbl> <fct>     <fct>    \n 1    39 4         0        \n 2    46 2         0        \n 3    48 1         0        \n 4    61 3         1        \n 5    46 3         0        \n 6    43 2         0        \n 7    63 1         1        \n 8    45 2         0        \n 9    52 1         0        \n10    43 1         0        \n# ℹ 4,125 more rows\n```\n\n\n:::\n:::\n\n\n## Univariate EDA\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-logistic-regression_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np1 <- ggplot(heart_disease, aes(x = high_risk, y = age)) +\n  geom_boxplot(fill = \"steelblue\") +\n  labs(x = \"High risk\",\n       y = \"Age\", \n       title = \"High risk vs. age\") + \n  coord_flip()\n\np2 <- ggplot(heart_disease, aes(x = education, fill = high_risk)) +\n  geom_bar(position = \"fill\", color = \"black\") +\n  labs(x = \"Education\",\n    fill = \"High risk\", \n    title = \"High risk vs. education\") +\n  scale_fill_viridis_d() +\n  theme(legend.position = \"bottom\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](18-logistic-regression_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Linear model?\n\nLet's consider the linear model $\\hat{\\mathbf{y}} = \\mathbf{X}\\hat{\\boldsymbol{\\beta}}$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](18-logistic-regression_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n::: question\nDoes the linear model make sense?\n:::\n\n## Binary response variable\n\nThe response variable $Y$ is a binary random variable such that the probability that $Y_i = 1$ is $\\pi$.\n\n$$\n\\begin{aligned}\n&P(Y_i= 1) = \\pi\\\\[8pt]\n&P(Y_i = 0) = 1 - \\pi\n\\end{aligned}\n$$\n\n. . .\n\nRecall in linear regression, we modeled the expected value of $Y_i$ given the predictors $E(\\mathbf{y}|\\mathbf{X}) = \\mathbf{X}\\boldsymbol{\\beta}$\n\n. . .\n\nNow we have a response variable, such that $E(Y_i | \\pi) = \\pi$\n\n## Let's try a new model\n\n::: question\nLet's say $\\pi = 0.5$. What does $E(Y_i | \\pi) = \\pi$ mean in the context of the data? Is this assumption realistic in practice?\n:::\n\n## Let's try a new model\n\nWe want to compute probabilities $\\pi$ based on the predictor variables (e.g., use an individual's age and education to evaluate their risk for heart disease).\n\nSuppose we try a model of the form\n\n$$\n\\pi_i = \\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\n$$\n\nwhere $x_i^\\mathsf{T}$ is the $i^{th}$ row of the design matrix $\\mathbf{X}$\n\n::: question\nWhat is wrong with using a model of this form?\n:::\n\n## Logit link function\n\nInstead of modeling $\\pi_i$ directly, we will model $\\text{logit}(\\pi_i) = \\text{log}\\big(\\frac{\\pi_i}{1 - \\pi_i}\\big)$ such that\n\n$$\n\\text{logit}(\\pi_i) = \\text{log}\\Big(\\frac{\\pi_i}{1 - \\pi_i}\\Big) = \\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\n$$\n\n. . .\n\nThe logit function links $E(Y_i | \\pi)$ to the predictors, so the logit is a **link function*.***\n\n## Logit function\n\nThe logit function is\n\n$$\n\\text{logit}(\\pi_i) = \\text{log}\\Big(\\frac{\\pi_i}{1 - \\pi_i}\\Big) $$\n\n::: question\n-   What happens to $\\text{logit}(\\pi_i)$ as $\\pi_i \\rightarrow 0$?\n\n-   What happens as $\\pi_i \\rightarrow 1$?\n:::\n\n## From logit to probability {.midi}\n\n**Logistic model** $$\\text{logit}(\\pi_i) = \\log\\big(\\frac{\\pi_i}{1-\\pi_i}\\big) = \\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}$$\n\n. . .\n\n**Odds** $$\\exp\\big\\{\\log\\big(\\frac{\\pi_i}{1 - \\pi_i}\\big)\\big\\} = \\frac{\\pi_i}{1-\\pi_i}$$\n\n. . .\n\n**Probability**\n\n$$\\pi_i = \\frac{\\exp\\{\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\}}{1 + \\exp\\{\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\}} = \\frac{1}{\\exp\\{-\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\} + 1}$$\n\n## Sigmoid function\n\nWe call this function relating the probability to the predictors a **sigmoid function** $$\n\\sigma(z) = \\frac{\\exp\\{z\\}}{1 + \\exp\\{z\\}}= \\frac{1}{1+\\text{exp}\\{-z\\}}.$$\n\nThis is the \"S\" curve produced by logistic regression.\n\n## Sigmoid function\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](18-logistic-regression_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Logistic regression\n\nWe want to use our data to find $\\hat{\\boldsymbol{\\beta}}$, so that we can predict the probability that $Y_i = 1$ given the predictors\n\n$$\n\\hat\\pi_i = \\frac{\\exp\\{\\mathbf{x}_i^\\mathsf{T}\\hat{\\boldsymbol\\beta}\\}}{ 1 + \\exp\\{\\mathbf{x}_i^\\mathsf{T}\\hat{\\boldsymbol\\beta}\\}}\n$$\n\n. . .\n\nWe derive $\\hat{\\boldsymbol{\\beta}}$ using **maximum likelihood estimation**\n\n## Likelihood {.midi}\n\nFor an individual observation**:**\n\n$$p(y_i | \\mathbf{X}, \\boldsymbol{\\beta}) = \\pi^{y_i}_i (1-\\pi_i)^{1-y_i}$$\n\n. . .\n\nThe likelihood is the joint density of $y_1, \\ldots, y_n$ as a function of the unknown $\\boldsymbol{\\beta}$\n\n. . .\n\n$$\\begin{aligned}L(\\boldsymbol{\\beta} | \\mathbf{X}, \\mathbf{y}) &= p(y_1, \\dots, y_n | \\mathbf{X}, \\boldsymbol{\\beta}) \\\\[8pt]\n& = \\prod_{i=1}^n p(y_i | \\mathbf{X}, \\boldsymbol{\\beta})  \\\\[8pt]\n & = \\prod_{i=1}^n \\pi_i^{y_i} (1-\\pi_i)^{1-y_i}\\end{aligned}$$\n\n## Log-likelihood\n\nWe use the log-likelihood to find the MLE for $\\boldsymbol{\\beta}$\n\nThe log-likelihood function for $\\boldsymbol\\beta$ is\n\n$$\n\\begin{aligned}\n\\log L(\\boldsymbol{\\beta} \\mid \\mathbf{X}, \\mathbf{y}) \n&= \\sum_{i=1}^n \\log\\left(\\pi_i^{y_i}(1-\\pi_i)^{1-y_i}\\right) \\\\[8pt]\n&= \\sum_{i=1}^n y_i \\log(\\pi_i) + (1-y_i)\\log(1-\\pi_i)\n\\end{aligned}\n$$\n\n## Log-likelihood {.midi}\n\nPlugging in $\\pi_i = \\frac{\\exp\\{\\mathbf{x}_i^\\mathsf{T} \\boldsymbol\\beta\\}}{1+\\exp\\{\\mathbf{x}_i^\\mathsf{T} \\boldsymbol\\beta\\}}$, we get\n\n$$\n\\begin{aligned}\n\\log L(\\boldsymbol{\\beta} \\mid \\mathbf{X}, \\mathbf{y}) = \\sum_{i=1}^n &y_i \\log\\left(\\frac{\\exp\\{\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\}}{1 + \\exp\\{\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\}}\\right) \\\\\n&+ (1 - y_i)\\log\\left(\\frac{1}{1 + \\exp\\{\\mathbf{x}_i^\\mathsf{T}\\boldsymbol{\\beta}\\}}\\right) \\end{aligned} $$ <br>\n\n$$= \\sum_{i=1}^n y_i \\mathbf{x}_i^\\mathsf{T} \\boldsymbol\\beta - \\sum_{i=1}^n \\log(1+ \\exp\\{\\mathbf{x}_i^\\mathsf{T} \\boldsymbol{\\beta}\\})$$\n\n## Finding the MLE\n\n-   Taking the derivative:\n\n$$\n\\begin{aligned}\n\\frac{\\partial \\log L}{\\partial \\boldsymbol\\beta} =\\sum_{i=1}^n y_i \\mathbf{x}_i^\\mathsf{T}\n&- \\sum_{i=1}^n \\frac{\\exp\\{\\mathbf{x}_i^\\mathsf{T} \\boldsymbol\\beta\\} \\mathbf{x}_i^\\mathsf{T}}{1+\\exp\\{\\mathbf{x}_i^\\mathsf{T} \\boldsymbol\\beta\\}}\n\\end{aligned}\n$$\n\n. . .\n\n-   If we set this to zero, there is no closed form solution.\n\n. . .\n\n-   R uses numerical approximation to find the MLE.\n\n## Logistic regression in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nheart_disease_fit <- glm(high_risk ~ age + education, \n                         data  = heart_disease, \n                         family = \"binomial\", \n                        control = glm.control(trace = TRUE)) # just to show estimation \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDeviance = 3336.175 Iterations - 1\nDeviance = 3300.661 Iterations - 2\nDeviance = 3300.136 Iterations - 3\nDeviance = 3300.135 Iterations - 4\nDeviance = 3300.135 Iterations - 5\n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#stop printing for future models\nuntrace(glm.fit)\n```\n:::\n\n\n## Logistic regression in R\n\n::: small\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1|2|3\"}\nheart_disease_fit <- glm(high_risk ~ age + education, \n                         data  = heart_disease, \n                         family = \"binomial\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n$$\n\\begin{aligned}\n\\log\\Big(\\frac{\\hat{\\pi}_i}{1-\\hat{\\pi}_i}\\Big) =& -5.385 + 0.073 \\times \\text{age}_i - 0.242\\times \\text{education2}_i \\\\\n&- 0.235\\times\\text{education3}_i - 0.020 \\times\\text{education4}_i\n\\end{aligned}\n$$ where $\\hat{\\pi}_i$ is the predicted probability an individual is high risk of having heart disease in the next 10 years\n:::\n\n## Interpretation in terms of log-odds\n\n::: small\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n:::\n\n`education4`: The predicted **log-odds** of being high risk for heart disease are 0.020 less for those with a college degree compared to those with some high school, **holding age constant.**\n\n. . .\n\n::: callout-warning\n## Interpretation in practice\n\nWe generally do not use the log-odds interpretation in practice.\n:::\n\n## Interpretation in terms of log-odds\n\n::: small\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n:::\n\n`age`: For each additional year in age, the predicted log-odds of being high risk for heart disease increase by 0.073, **holding education level constant.**\n\n. . .\n\n::: callout-warning\n## Interpretation in practice\n\nWe generally do not use the log-odds interpretation in practice.\n:::\n\n## Interpretation in terms of odds\n\n<div>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n</div>\n\n::: question\nInterpret the following in terms of the odds:\n\n-   `education4`\n\n-   `age`\n:::\n\n## Interpretation in terms of odds {.midi}\n\n-   $\\exp\\{\\hat{\\beta}_j\\}$ is the **(adjusted) odds ratio**\n\n    -   Level $k$ versus the baseline for categorical predictors\n\n    -   $x_{j + 1}$ versus $x_j$ for quantitative predictors\n\n-   We can also interpret the odds ratio in terms of a percent difference\n\n    \"Odds multiplying by $\\exp\\{\\hat{\\beta}_j\\}$\" is equivalent to \"the odds changing by $(\\exp\\{\\hat{\\beta}_j\\} - 1) \\times 100$ %\"\n\n## Recap\n\n-   Introduced logistic regression for binary response variable\n\n-   Used maximum likelihood estimation to derive $\\hat{\\boldsymbol{\\beta}}$\n\n-   Interpreted coefficients of logistic regression model\n\n## Next class\n\n-   Logistic regression: prediction and classification\n\n-   Complete [Lecture 19 prepare](../prepare/prepare-lec19.html)\n",
    "supporting": [
      "18-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}