{
  "hash": "9adbb6bcdff27f20398759617d4cea90",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple linear regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"01-22-2026\"\ndate-format: \"MMMM DD, YYYY\"\nfooter: \"[🔗 sta221-sp26.github.io](https://sta221-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 05-mlr-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\n\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n## Announcements\n\n-   HW 01 - **due Thursday, January 29 at 11:59pm**\n\n## Topics\n\n-   Introducing multiple linear regression\n\n    -   Exploratory data analysis for multiple linear regression\n\n    -   Fitting the least squares line\n\n    -   Interpreting coefficients for quantitative predictors\n\n    -   Prediction\n\n-   Comparing models\n\n## Computing setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n## Data: Peer-to-peer lender\n\nToday's data is a sample of 50 loans made through a peer-to-peer lending club. The data is in the `loan50` data frame in the **openintro** R package.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 4\n   annual_income debt_to_income verified_income interest_rate\n           <dbl>          <dbl> <fct>                   <dbl>\n 1         59000         0.558  Not Verified            10.9 \n 2         60000         1.31   Not Verified             9.92\n 3         75000         1.06   Verified                26.3 \n 4         75000         0.574  Not Verified             9.92\n 5        254000         0.238  Not Verified             9.43\n 6         67000         1.08   Source Verified          9.92\n 7         28800         0.0997 Source Verified         17.1 \n 8         80000         0.351  Not Verified             6.08\n 9         34000         0.698  Not Verified             7.97\n10         80000         0.167  Source Verified         12.6 \n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\n## Variables\n\n**Predictors**:\n\n::: nonincremental\n-   `annual_income`: Annual income\n-   `debt_to_income`: Debt-to-income ratio, i.e. the percentage of a borrower's total debt divided by their total income\n-   `verified_income`: Whether borrower's income source and amount have been verified (`Not Verified`, `Source Verified`, `Verified`)\n:::\n\n**Response**: `interest_rate`: Interest rate for the loan\n\n## Response: `interest_rate`\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  Min| Median|  Max|   IQR|\n|----:|------:|----:|-----:|\n| 5.31|   9.93| 26.3| 5.755|\n\n\n:::\n:::\n\n\n## Predictors {.small}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Data manipulation 1: Rescale income\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(annual_income_th = annual_income / 1000)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n. . .\n\n::: question\nWhy did we rescale income?\n:::\n\n## Outcome vs. predictors {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-mlr_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n. . .\n\n**Goal**: Use these predictors in a single model to understand variability in interest rate.\n\n. . .\n\n::: question\nWhy do we want to use a single model versus 3 separate simple linear regression models?\n:::\n\n# Multiple linear regression (MLR)\n\n## Multiple linear regression (MLR)\n\nBased on the analysis goals, we will use a **multiple linear regression** model of the following form\n\n$$\n\\begin{aligned}\\text{interest_rate} ~ = \n\\beta_0 & + \\beta_1 ~ \\text{debt_to_income} \\\\ & + \\beta_2 ~ \\text{verified_income} \\\\ &+ \\beta_3~ \\text{annual_income_th} \\\\\n& +\\epsilon, \\quad \\epsilon \\sim N(0, \\sigma^2_{\\epsilon})\n\\end{aligned}\n$$\n\n## Multiple linear regression\n\n**Recall:** The simple linear regression model\n\n$$\nY = \\beta_0 + \\beta_1~ X + \\epsilon\n$$\n\n. . .\n\nThe form of the multiple linear regression model is\n\n$$\nY = \\beta_0 + \\beta_1X_1 +  \\dots + \\beta_pX_p + \\epsilon\n$$\n\n<br>\n\n. . .\n\nTherefore,\n\n$$\nE(Y|X_1, \\ldots, X_p) = \\beta_0 + \\beta_1X_1 +  \\dots + \\beta_pX_p\n$$\n\n## Fitting the least squares line\n\nSimilar to simple linear regression, we want to find estimates for $\\beta_0, \\beta_1, \\ldots, \\beta_p$ that minimize\n\n$$\n\\sum_{i=1}^{n}\\epsilon_i^2 = \\sum_{i=1}^n[y_i - \\hat{y}_i]^2 = \\sum_{i=1}^n[y_i - (\\beta_0 + \\beta_1x_{i1} + \\dots + \\beta_px_{ip})]^2\n$$\n\n<br>\n\n. . .\n\nThe calculations can be very tedious, especially if $p$ is large\n\n## Matrix form of multiple linear regression\n\nSuppose we have $n$ observations, a quantitative response variable, and $p$ \\> 1 predictors $$\n\\underbrace{\n\\begin{bmatrix}\ny_1 \\\\\n\\vdots \\\\\ny_n\n\\end{bmatrix} }_\n{\\mathbf{y}} \\hspace{3mm}\n= \n\\hspace{3mm}\n\\underbrace{\n\\begin{bmatrix}\n1 &x_{11} & \\dots & x_{1p}\\\\\n\\vdots & \\vdots &\\ddots & \\vdots \\\\\n1 &  x_{n1} & \\dots &x_{np}\n\\end{bmatrix}\n}_{\\mathbf{X}}\n\\hspace{2mm}\n\\underbrace{\n\\begin{bmatrix}\n\\beta_0 \\\\\n\\beta_1 \\\\\n\\vdots \\\\\n\\beta_p\n\\end{bmatrix}\n}_{\\boldsymbol{\\beta}}\n\\hspace{3mm}\n+\n\\hspace{3mm}\n\\underbrace{\n\\begin{bmatrix}\n\\epsilon_1 \\\\\n\\vdots\\\\\n\\epsilon_n\n\\end{bmatrix}\n}_\\boldsymbol{\\epsilon}\n$$\n\n::: question\nWhat are the dimensions of $\\mathbf{y}$, $\\mathbf{X}$, $\\boldsymbol{\\beta}$, $\\boldsymbol{\\epsilon}$?\n:::\n\n## Matrix form of multiple linear regression\n\nAs with simple linear regression, we have\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\epsilon}\n$$\n\n. . .\n\nGeneralizing the derivations from SLR to $p > 2$, we have\n\n$$\n\\hat{\\boldsymbol{\\beta}} = (\\mathbf{X}^\n \\mathsf{T}\\mathbf{X})^{-1}\\mathbf{X}^\\mathsf{T}\\mathbf{y}\n$$\n\nas before.\n\n## Model fit in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nint_fit <- lm(interest_rate ~ debt_to_income + verified_income  + annual_income_th,\n              data = loan50)\n\ntidy(int_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value|\n|:------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                    |   10.726|     1.507|     7.116|   0.000|\n|debt_to_income                 |    0.671|     0.676|     0.993|   0.326|\n|verified_incomeSource Verified |    2.211|     1.399|     1.581|   0.121|\n|verified_incomeVerified        |    6.880|     1.801|     3.820|   0.000|\n|annual_income_th               |   -0.021|     0.011|    -1.804|   0.078|\n\n\n:::\n:::\n\n\n## Model equation\n\n$$\n\\begin{align}\\hat{\\text{interest_rate}} =  10.726 &+0.671 \\times \\text{debt_to_income}\\\\\n&+ 2.211 \\times \\text{source_verified}\\\\  \n&+ 6.880 \\times \\text{verified}\\\\\n& -0.021 \\times \\text{annual_income_th}\n\\end{align}\n$$\n\n::: callout-note\nWe will talk about why there are only two terms in the model for `verified_income` soon!\n:::\n\n## Interpreting $\\hat{\\beta}_j$\n\n-   The estimated coefficient $\\hat{\\beta}_j$ is the expected change in the mean of $Y$ when $X_j$ increases by one unit, <i><b>holding the values of all other predictor variables constant</b></i>.\n\n. . .\n\n-   **Example:** The estimated coefficient for `debt_to_income` is 0.671. This means for each point in an borrower's debt to income ratio, the interest rate on the loan is expected to be greater by 0.671%, on average, holding annual income and income verification constant.\n\n## Interpreting $\\hat{\\beta}_j$\n\n::: question\nThe estimated coefficient for `annual_income_th` is -0.021. Interpret this coefficient in the context of the data.\n:::\n\n<br>\n\n<!--# Make ed discussion poll-->\n\n::: question\nWhy do we need to include a statement about holding all other predictors constant?\n:::\n\n## Interpreting $\\hat{\\beta}_0$\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:------------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)                    |   10.726|     1.507|     7.116|   0.000|    7.690|    13.762|\n|debt_to_income                 |    0.671|     0.676|     0.993|   0.326|   -0.690|     2.033|\n|verified_incomeSource Verified |    2.211|     1.399|     1.581|   0.121|   -0.606|     5.028|\n|verified_incomeVerified        |    6.880|     1.801|     3.820|   0.000|    3.253|    10.508|\n|annual_income_th               |   -0.021|     0.011|    -1.804|   0.078|   -0.043|     0.002|\n\n\n:::\n:::\n\n\n. . .\n\n:::: question\n::: midi\nDescribe the subset of borrowers who are expected to get an interest rate of 10.726% based on our model. Is this interpretation meaningful? Why or why not?\n:::\n::::\n\n## Prediction\n\n::: question\nWhat is the predicted interest rate for an borrower with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000?\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n10.726 + 0.671 * 0.558 + 2.211 * 0 + 6.880 * 0 - 0.021 * 59\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.861418\n```\n\n\n:::\n:::\n\n\n. . .\n\nThe predicted interest rate for an borrower with with an debt-to-income ratio of 0.558, whose income is not verified, and who has an annual income of \\$59,000 is 9.86%.\n\n## Prediction in R {.midi}\n\nJust like with simple linear regression, we can use the `predict()` function in R to calculate the appropriate intervals for our predicted values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_borrower <- tibble(\n  debt_to_income  = 0.558, \n  verified_income = \"Not Verified\", \n  annual_income_th = 59\n)\n\npredict(int_fit, new_borrower)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n9.890888 \n```\n\n\n:::\n:::\n\n\n::: callout-note\nDifference in predicted value due to rounding the coefficients on the previous slide.\n:::\n\n## Cautions\n\n-   **Do not extrapolate!** Because there are multiple predictor variables, there is the potential to extrapolate in many directions\n-   The multiple regression model only shows **association, not causality**\n    -   To show causality, you must have a carefully designed experiment or carefully account for confounding variables in an observational study (causal inference)\n\n# Model comparison\n\n## Model evaluation: RMSE & $R^2$\n\n-   **Root mean square error, RMSE**: A measure of the average error (average difference between observed and predicted values of the outcome)\n\n-   **R-squared**, $R^2$ : Percentage of variability in the outcome explained by the regression model\n\n## Comparing models {.small}\n\nLet's consider the following models:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                                            | Model 1| Model 2|\n|:-----------------------------------------------|-------:|-------:|\n|(Intercept)                                     |  10.726|   9.560|\n|debt_to_income                                  |   0.671|   0.691|\n|verified_incomeSource Verified                  |   2.211|   3.577|\n|verified_incomeVerified                         |   6.880|   9.923|\n|annual_income_th                                |  -0.021|  -0.007|\n|verified_incomeSource Verified:annual_income_th |      NA|  -0.016|\n|verified_incomeVerified:annual_income_th        |      NA|  -0.032|\n\n\n:::\n:::\n\n\n<br>\n\n<center>**How do we decide which model to choose?**</center>\n\n## Comparing models\n\n::: incremental\n-   When comparing models, do we prefer the model with the lower or higher RMSE?\n\n-   Though we use $R^2$ to assess the model fit, it is generally unreliable for comparing models with different number of predictors. Why?\n\n    -   $R^2$ will stay the same or increase as we add more variables to the model.\n\n    -   If we only use $R^2$ to choose a best fit model, we will be prone to choose the model with the most predictor variables.\n:::\n\n## Adjusted $R^2$\n\n-   **Adjusted** $R^2$: measure that includes a penalty for unnecessary predictor variables\n-   Similar to $R^2$, it is a measure of the amount of variation in the response that is explained by the regression model\n-   Use the `glance()` function to get $Adj. R^2$ in R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(int_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.215841\n```\n\n\n:::\n:::\n\n\n## $R^2$ and Adjusted $R^2$\n\n$$R^2 = \\frac{SSM}{SST} = 1 - \\frac{SSR}{SST}$$\n\n<br>\n\n. . .\n\n$$R^2_{adj} = 1 - \\frac{SSR/(n-p-1)}{SST/(n-1)}$$\n\nwhere\n\n-   $n$ is the number of observations used to fit the model\n\n-   $p$ is the number of non-intercept terms in the model\n\n## Using $R^2$ and Adjusted $R^2$\n\n-   Adjusted $R^2$ can be used as a quick assessment to compare the fit of multiple models; however, it should not be the only assessment\n-   Use $R^2$ when describing the relationship between the response and predictor variables\n\n## Comparing interest rate models\n\n::::: columns\n::: {.column width=\"50%\"}\n**Model 1**\n\n**Model without interaction**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# r-squared\nglance(int_fit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.279854\n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adj-r-squared\nglance(int_fit)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.215841\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Model 2**\n\n**Model with interaction**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# r-squared\nglance(int_fit_2)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2963437\n```\n\n\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adj-r-squared\nglance(int_fit_2)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1981591\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n## Recap\n\n-   Showed exploratory data analysis for multiple linear regression\n\n-   Used least squares to fit the regression line\n\n-   Interpreted the coefficients for quantitative predictors\n\n-   Predicted the response for new observations\n\n-   Introduced $Adj. R^2$ for comparing models\n",
    "supporting": [
      "05-mlr_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}