{
  "hash": "70c7def2f9c3b632229dea82ed58af93",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Inference for regression\"\nsubtitle: \"Cont'd\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2025-02-11\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 221 - Spring 2025](https://sta221-sp25.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 10-inference-pt3-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements\n\n-   Research topics due TODAY at 11:59pm on GitHub\n\n-   HW 02 due Thursday at 11:59pm\n\n-   [Statistics experience](../hw/stats-experience.html) due **Tuesday, April 22**\n\n## Exam 01\n\n-   50 points total\n\n    -   in-class: 35-40 points\n    -   take-home: 10 - 15 points\n\n-   In-class (35 -40 pts): 75 minutes during February 18 lecture\n\n    -   Will be randomly assigned to exam room\n\n-   Take-home (10 -15 pts): released after class on Tuesday\n\n-   If you miss any part of the exam for an excused absence (with academic dean’s note or other official documentation), your Exam 02 score will be counted twice\n\n## Resources\n\n-   [Exam 01 practice](../exam-01-practice.html)\n\n-   [Lecture recordings](https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=0b5392d5-d61b-465a-80eb-b25e014a75a9)\n\n-   Prepare readings (see course schedule)\n\n-   Lecture notes (use search bar to find specific topics)\n\n-   AEs\n\n-   Assignments\n\n## Topics\n\n-   Conduct inference on a single coefficient\n\n## Computing setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)  \nlibrary(tidymodels)  \nlibrary(knitr)       \nlibrary(kableExtra)  \nlibrary(patchwork)   \n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n## Data: NCAA Football expenditures {.midi}\n\nToday's data come from [Equity in Athletics Data Analysis](https://ope.ed.gov/athletics/#/datafile/list) and includes information about sports expenditures and revenues for colleges and universities in the United States. This data set was featured in a [March 2022 Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md).\n\nWe will focus on the 2019 - 2020 season expenditures on football for institutions in the NCAA - Division 1 FBS. The variables are :\n\n-   `total_exp_m`: Total expenditures on football in the 2019 - 2020 academic year (in millions USD)\n\n-   `enrollment_th`: Total student enrollment in the 2019 - 2020 academic year (in thousands)\n\n-   `type`: institution type (Public or Private)\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfootball <- read_csv(\"data/ncaa-football-exp.csv\")\n```\n:::\n\n\n## Regression model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexp_fit <- lm(total_exp_m ~ enrollment_th + type, data = football)\ntidy(exp_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n# Inference for a single coefficient\n\n## Inference for $\\beta_j$\n\nWe often want to conduct inference on individual model coefficients\n\n-   **Hypothesis test:** Is there a linear relationship between the response and $x_j$?\n\n-   **Confidence interval**: What is a plausible range of values $\\beta_j$ can take?\n\n## Sampling distribution of $\\hat{\\beta}$ {.midi}\n\n-   A **sampling distribution** is the probability distribution of a statistic for a large number of random samples of size $n$ from a population\n\n-   The sampling distribution of $\\hat{\\boldsymbol{\\beta}}$ is the probability distribution of the estimated coefficients if we repeatedly took samples of size $n$ and fit the regression model\n\n$$\n\\hat{\\boldsymbol{\\beta}} \\sim N(\\boldsymbol{\\beta}, \\sigma^2_\\epsilon(\\mathbf{X}^\\mathsf{T}\\mathbf{X})^{-1})\n$$\n\nThe estimated coefficients $\\hat{\\boldsymbol{\\beta}}$ are **normally distributed** with\n\n$$\nE(\\hat{\\boldsymbol{\\beta}}) = \\boldsymbol{\\beta} \\hspace{10mm} Var(\\hat{\\boldsymbol{\\beta}}) = \\sigma^2_{\\epsilon}(\\boldsymbol{X}^\\mathsf{T}\\boldsymbol{X})^{-1}\n$$\n\n## Sampling distribution of $\\hat{\\beta}_j$\n\n$$\n\\hat{\\boldsymbol{\\beta}} \\sim N(\\boldsymbol{\\beta}, \\sigma^2_\\epsilon(\\mathbf{X}^\\mathsf{T}\\mathbf{X})^{-1})\n$$\n\nLet $\\mathbf{C} = (\\mathbf{X}^\\mathsf{T}\\mathbf{X})^{-1}$. Then, for each coefficient $\\hat{\\beta}_j$,\n\n::: incremental\n-   $E(\\hat{\\beta}_j) = \\boldsymbol{\\beta}_j$, the $j^{th}$ element of $\\boldsymbol{\\beta}$\n\n-   $Var(\\hat{\\beta}_j) = \\sigma^2_{\\epsilon}C_{jj}$\n\n-   $Cov(\\hat{\\beta}_i, \\hat{\\beta}_j) = \\sigma^2_{\\epsilon}C_{ij}$\n:::\n\n# Hypothesis test for $\\beta_j$\n\n## Steps for a hypothesis test\n\n1.  State the null and alternative hypotheses.\n2.  Calculate a test statistic.\n3.  Calculate the p-value.\n4.  State the conclusion.\n\n<br>\n\n::: question\nLet's walk through the steps to test $\\beta_j$, the coefficient for `typePublic` .\n:::\n\n## Hypothesis test for $\\beta_j$: Hypotheses\n\n-   **Null:** There is no linear relationship between institution type and football expenditure, after adjusting for enrollment $H_0: \\beta_j = 0$\n\n-   **Alternative:** There is a linear relationship between institution type and football expenditure, after adjusting for enrollment $H_a: \\beta_j \\neq 0$\n\n## Hypothesis test for $\\beta_j$: Test statistic {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n**Test statistic:** Number of standard errors the estimate is away from the null\n\n$$\n\\text{Test Statistic} = \\frac{\\text{Estimate - Null}}{\\text{Standard error}} = \\frac{-13.226 - 0}{3.153} = -4.195 \\\\\n$$\n\n. . .\n\nThis means the estimated slope of -13.226 is 4.195 standard errors below the hypothesized mean of 0.\n\n## Hypothesis test for $\\beta_j$: p-value {.midi}\n\n-   The test statistic follows a $t$ distribution with 124 degrees of freedom.\n\n$$\np-value = P(|T| > |-4.195|)\n$$\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n2 * pt(4.195, df = nrow(football) - 2 - 1, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.00005153923\n```\n\n\n:::\n:::\n\n\n<br>\n\n. . .\n\nGiven $\\beta_j = 0$ ( $H_0$ is true), the probability of observing a slope of -13.226 or more extreme is $\\approx 0$ .\n\n## Hypothesis test for $\\beta_j$: Conclusion\n\n-   The p-value is $\\approx 0$, so we **reject** $H_0$.\n\n-   The data provide sufficient evidence that $\\beta_j \\neq 0$, meaning evidence there is a linear relationship between institution type and football expenditure, after adjusting for enrollment.\n\n# Confidence interval for $\\beta_j$\n\n## Confidence interval for $\\beta_j$ {.midi}\n\n::: incremental\n-   A plausible range of values for a population parameter is called a **confidence interval**\n\n-   Using only a single point estimate is like fishing in a murky lake with a spear, and using a confidence interval is like fishing with a net\n\n    -   We can throw a spear where we saw a fish but we will probably miss, if we toss a net in that area, we have a good chance of catching the fish\n\n    -   Similarly, if we report a point estimate, we probably will not hit the exact population parameter, but if we report a range of plausible values we have a good shot at capturing the parameter\n:::\n\n## What \"confidence\" means {.midi}\n\n::: incremental\n-   We will construct $C\\%$ confidence intervals.\n\n    -   The confidence level impacts the width of the interval\n\n-   \"Confident\" means if we were to take repeated samples of the same size as our data, fit regression lines using the same predictors, and calculate $C\\%$ Cs for the coefficient of $x_j$, then $C\\%$ of those intervals will contain the true value of the coefficient $\\beta_j$\n\n-   Balance precision and accuracy when selecting a confidence level\n:::\n\n## Confidence interval for $\\beta_j$\n\n$$\n\\text{Estimate} \\pm \\text{ (critical value) } \\times \\text{SE}\n$$\n\n<br>\n\n. . .\n\n$$\n\\hat{\\beta}_1 \\pm t^* \\times SE({\\hat{\\beta}_j})\n$$\n\nwhere $t^*$ is calculated from a $t$ distribution with $n-p-1$ degrees of freedom\n\n## Confidence interval: Critical value\n\n::: {.fragment fragment-index=\"1\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 95%\nqt(0.975, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.97928\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n::: {.fragment fragment-index=\"2\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 90%\nqt(0.95, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.657235\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n::: {.fragment fragment-index=\"3\"}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confidence level: 99%\nqt(0.995, df = nrow(football) - 2 - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.61606\n```\n\n\n:::\n:::\n\n:::\n\n## 95% CI for $\\beta_j$: Calculation\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value|\n|:-------------|--------:|---------:|---------:|-------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|\n|enrollment_th |    0.780|     0.110|     7.074|       0|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|\n\n\n:::\n:::\n\n\n## 95% CI for $\\beta_j$ in R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(exp_fit, conf.int = TRUE, conf.level = 0.95) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term          | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)   |   19.332|     2.984|     6.478|       0|   13.426|    25.239|\n|enrollment_th |    0.780|     0.110|     7.074|       0|    0.562|     0.999|\n|typePublic    |  -13.226|     3.153|    -4.195|       0|  -19.466|    -6.986|\n\n\n:::\n:::\n\n\n<br>\n\n**Interpretation**: We are 95% confident that for each additional 1,000 students enrolled, the institution's expenditures on football will be greater by \\$562,000 to \\$999,000, on average, holding institution type constant.\n\n# Application exercise\n\n::: appex\n📋 [sta221-sp25.netlify.app/ae/ae-03-inference.html](../ae/ae-03-inference.html)\n:::\n\n## Recap\n\n-   Conducted hypothesis tests for a single coefficient $\\beta_j$\n\n-   Computed and interpreted confidence intervals for a single coefficient $\\beta_j$\n\n## Next class\n\n-   Exam 01 review\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}